"""Atomic observation schema.

An Observation is the smallest unit of evidence.
It is a fact about the world, not an inference.

OBSERVATION:
    CSMegastore lists Testo 0564 5501 at NOK 6,532.

INFERENCE:
    Norway is less supply-empty than public search suggested.

DECISION:
    Do not advance MERCHANT_GAP_VERIFIED.

Observations are immutable once created.
Inferences and decisions are derived, not stored as observations.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


class EvidenceGrade(str, Enum):
    """How reliable is this observation?

    A: Direct measurement (our own store data, our own SERP scrape)
    B: Multiple independent sources agree
    C: Single credible source (official site, major retailer)
    D: Weak source (forum post, social media, cached page)
    """

    A = "A"
    B = "B"
    C = "C"
    D = "D"


class EvidenceSource(str, Enum):
    """Where did this observation come from?"""

    SERP = "serp"
    RETAILER_SITE = "retailer_site"
    COMPARISON_SITE = "comparison_site"
    SUPPLIER = "supplier"
    MARKETPLACE = "marketplace"
    FORUM = "forum"
    NEWS = "news"
    REGULATORY = "regulatory"
    OUR_STORE = "our_store"
    SEARCH_CONSOLE = "search_console"
    MERCHANT_CENTER = "merchant_center"
    MANUAL = "manual"


class Observation(BaseModel):
    """An atomic fact about the world.

    This is the input to all pipelines.
    Observations are created by probes, imported from emails,
    or generated by agents.

    Key principle: this is a FACT, not an opinion.
    """

    observation_id: str = Field(default_factory=lambda: f"O-{uuid.uuid4().hex[:12]}")

    # What is this about?
    entity_type: str  # "candidate", "supplier", "product", "market", "ecosystem"
    entity_id: str  # e.g. "NO-TESTO-550S-001"

    # What field does this observation affect?
    field: str  # e.g. "dealer_price", "merchant_count", "demand_score"

    # What did we observe?
    value: str | float | int | bool  # The observed value
    unit: Optional[str] = None  # e.g. "NOK", "EUR", "count", "percentage"

    # Source provenance
    source: EvidenceSource
    source_url: Optional[str] = None
    source_grade: EvidenceGrade = EvidenceGrade.C
    source_name: Optional[str] = None  # e.g. "CSMegastore", "Max Sievert"

    # Temporal evidence contract
    # event_time: when the event actually happened
    # published_at: when the source published it
    # observed_at: when GeoDrop observed it
    # available_at: when it became available for decision-making
    # ingested_at: when it was ingested into the system
    event_time: Optional[datetime] = None
    published_at: Optional[datetime] = None
    observed_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    available_at: Optional[datetime] = None
    ingested_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    # Independence tracking (prevents double-counting)
    independence_cluster: Optional[str] = None  # Groups related observations
    independent_source_count: int = 1  # How many independent sources?

    # Raw evidence (for audit trail)
    raw_snapshot: Optional[str] = None  # Raw text/HTML snapshot

    # Metadata
    probe_id: Optional[str] = None  # Which probe generated this?
    hypothesis_id: Optional[str] = None  # Which hypothesis does this test?
    candidate_id: Optional[str] = None  # Which candidate does this affect?

    # Tags for filtering
    tags: list[str] = Field(default_factory=list)

    model_config = {"frozen": True}  # Observations are immutable


class UnknownField(BaseModel):
    """A field whose value we don't know.

    Unknowns are first-class objects, not nulls.
    They tell downstream agents: stop pretending we know this.

    Example:
        field: "dealer_price"
        why_unknown: "Requires dealer application to Max Sievert"
        decision_dependency: "Cannot calculate margin without this"
        resolution_path: "Email Max Sievert with 1/5/10-unit quote request"
        estimated_resolution_cost: "15 minutes of human time"
    """

    unknown_id: str = Field(default_factory=lambda: f"U-{uuid.uuid4().hex[:12]}")
    candidate_id: str
    field: str
    why_unknown: str
    decision_dependency: str  # What decision is blocked by this unknown?
    resolution_path: str  # How can this be resolved?
    estimated_resolution_cost: Optional[str] = None  # Time/money/effort

    # Research EVI for this unknown
    probability_of_resolve: Optional[float] = None  # 0-1
    decision_impact: Optional[float] = None  # 0-1, how much does this change the decision?
    candidate_value: Optional[float] = None  # 0-1, how valuable is this candidate?
    research_cost: Optional[float] = None  # 0-1, how expensive is this research?

    # Status
    is_blocked: bool = False  # Requires external action?
    external_action_required: Optional[str] = None  # What human must do?
    contact_info: Optional[str] = None  # Who to contact?

    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def evi(self) -> Optional[float]:
        """Expected Value of Information for this unknown.

        EVI = P(resolve) * decision_impact * candidate_value / research_cost

        Higher EVI = more valuable to research next.
        """
        if (
            self.probability_of_resolve is None
            or self.decision_impact is None
            or self.candidate_value is None
            or self.research_cost is None
            or self.research_cost == 0
        ):
            return None
        return (
            self.probability_of_resolve
            * self.decision_impact
            * self.candidate_value
            / self.research_cost
        )
